MyWeb/Controllers/ListController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MyWeb.Models;


namespace MyWeb.Controllers
{
    public class ListController : Controller
    {
        private ModelContext db = new ModelContext();
        // GET: Default
        //列表
        public ActionResult Index()
        {

            return View(db.DbSet_WenZhang.ToList());
        }
        public ActionResult ListPanel(int skipCount, int takeCount)
        {
            //var m = from us in db.DbSet_WenZhang where us.BiaoTi == "中国" && us.JianYao == "中国" select us;
            var m = from us in db.DbSet_WenZhang  select us;
            //if (m.Count() != 0)
            //{

            //}
          
            var list = m.ToList().Skip(skipCount).Take(takeCount).ToList();
            return PartialView(list);
        }
 

        // GET: Default/Details/5
        //详细内容
        public ActionResult Details(int id)
        {
            return View();
        }

    }
}

MyWeb/Controllers/MobileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MyWeb.Models;
using System.Net;

namespace MyWeb.Controllers
{
    public class MobileController : Controller
    {
        private ModelContext db = new ModelContext();
        // GET: Default
        //列表全部数据
        public ActionResult Index()
        {
            return View(db.DbSet_WenZhang.ToList());
        }
        // GET: Mobile/ListPanel/n,m
        //列表加载更多，从第N条到第M条数据
        public ActionResult ListPanel(int skipCount, int takeCount)
        {
            //var m = from us in db.DbSet_WenZhang where us.BiaoTi == "中国" && us.JianYao == "中国" select us;
            var m = from us in db.DbSet_WenZhang select us;
            var list = m.ToList().Skip(skipCount).Take(takeCount).ToList();
            return PartialView(list);
        }
        // GET: Mobile/AboutInfo
        //关于信息页面
        public ActionResult AboutInfo()
        {
            return View();
        }

        // GET: Mobile/Details/5
        //文章详细页面
        public ActionResult Details(int? id)
        {
            Console.WriteLine("aaaaaaaaaaaaa"+ id);
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            WenZhang wenZhang = db.DbSet_WenZhang.Find(id);
            if (wenZhang == null)
            {
                return HttpNotFound();
            }
            return PartialView(wenZhang);
        }

    }
}

MyWeb/Views/Mobile/AboutInfo.cshtml
@model IEnumerable<MyWeb.Models.WenZhang>
@{Layout = null;}
<div class="mui-content-padded">
    <h4 style="margin-top:20px;">美文介绍</h4>
    <p>
        这款APP是自己学习web而做的，开始学习web后才知道牵扯很多知识点，如：Html5、Css、Js、服务端Mvc等。
    </p>
    <p>
        前端采用了mui框架，这是一个可以方便开发出高性能App的框架，也是目前最接近原生App效果的框架。
    </p>
    <h4>新手指南</h4>
    <p>
        若想详细了解Hello MUI的源码及工作原理，可从<a href="http://www.dcloud.io">Dcloud官网</a>下载Hbuilder，选择新建“移动APP”，并选择“Hello MUI”工程模板，创建工程；然后通过数据线将手机连接上电脑，点击运行，就可以在手机上体验MUI的各项能力。
    </p>
    <p>
        若要使用MUI进行移动APP开发，可通过Hbuilder，新建“移动APP”，并选择“MUI”工程模板，该模板已内置MUI相关的资源文件。
    </p>
    <p>更多详细介绍，请到<a href="http://dcloudio.github.io/mui">mui官网</a>查看；</p>
    <h4>版本介绍</h4>
    <p>当前版本为2.6.0，可到<a href="https://github.com/dcloudio/mui">Github</a>上获取最新版本。</p>
    <h4>License</h4>
    <p>
        mui遵循MIT License，源码已提交至Github，<a href="https://github.com/dcloudio/mui">点击查看</a>;
    </p>
</div>

MyWeb/Views/Mobile/Details.cshtml
@model MyWeb.Models.WenZhang
@Html.Raw(@Model.ZhengWenNeiRong)

MyWeb/Views/Mobile/Index.cshtml
@model IEnumerable<MyWeb.Models.WenZhang>

@{
    ViewBag.Title = "Index1";
    Layout = "~/Views/Shared/_LayoutMobile.cshtml";
}

@*显示部分视图*@
@*<ul class="mui-table-view">
    @{Html.RenderAction("ListPanel", "List", new { skipCount = 3, takeCount = 4 });}
</ul>*@

@Html.ActionLink("详细", "Details", new { id = 1 }) |

<ul class="mui-table-view">
    @foreach (var item in Model)
    {
        var imgsrc = "http://192.168.1.83/images/" + item.JianYaoTuPian;
        <li class="mui-table-view-cell mui-media ">
            <a href="javascript:;" id = @item.ID >
                <img class="mui-media-object mui-pull-left" src=@imgsrc>
                <div class="mui-media-body">
                    <h5 class="my-css-bt-color">@Html.DisplayFor(modelItem => item.BiaoTi)</h5>
                    <p class="mui-h mui-ellipsis">@Html.DisplayFor(modelItem => item.JianYao)</p>
                </div>
                <div class="mui-media-body mui-bottom  mui-pull-right my-css-xx-font">
                    <span class="iconfont icon-yulan">
                        <span class="my-css-tb-font">@Html.DisplayFor(modelItem => item.YueDuLiang)</span>
                    </span>
                    <span class="iconfont icon-huifu">
                        <span class="my-css-tb-font">@Html.DisplayFor(modelItem => item.PingLunLiang)</span>
                    </span>
                    <span class="iconfont icon-xin">
                        <span class="my-css-tb-font">@Html.DisplayFor(modelItem => item.ShouCangLiang)</span>
                    </span>
                </div>
            </a>
        </li>
    }
</ul>

<div class="list_loading">
    <i></i>
    <span>努力加载中...</span>
</div>

MyWeb/Views/Mobile/ListPanel.cshtml
@model IEnumerable<MyWeb.Models.WenZhang>
@foreach (var item in Model)
{
    var imgsrc = "http://192.168.1.83/images/" + item.JianYaoTuPian;
    <li class="mui-table-view-cell mui-media ">
        <a href="javascript:;"  id = @item.ID>
            <img class="mui-media-object mui-pull-left" src=@imgsrc>
            <div class="mui-media-body">
                <h5 class="my-css-bt-color">@Html.DisplayFor(modelItem => item.BiaoTi)</h5>
                <p class="mui-h mui-ellipsis">@Html.DisplayFor(modelItem => item.JianYao)</p>
            </div>
            <div class="mui-media-body mui-bottom  mui-pull-right my-css-xx-font">
                <span class="iconfont icon-yulan">
                    <span class="my-css-tb-font">@Html.DisplayFor(modelItem => item.YueDuLiang)</span>
                </span>
                <span class="iconfont icon-huifu">
                    <span class="my-css-tb-font">@Html.DisplayFor(modelItem => item.PingLunLiang)</span>
                </span>
                <span class="iconfont icon-xin">
                    <span class="my-css-tb-font">@Html.DisplayFor(modelItem => item.ShouCangLiang)</span>
                </span>
            </div>
        </a>
    </li>
}